name: Test the built package

on:
  push:
    branches: ["*"]
    tags-ignore: ["v*.*.*"]
  pull_request:

jobs:
  test-built:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 1. Build wheel + sdist into ./dist
      - name: Install build & build package
        run: |
          python -m pip install --upgrade pip build
          python -m build
          ls dist
          test -f dist/*.whl

      # 2. Install the wheel we just built (NOT the local source)
      - name: Install wheel & test deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install dist/*.whl
          python -m pip install pytest
          

      # 3. Run tests in a temporary directory to avoid importing the repo source
      - name: Run pytest against installed package
        run: |
          mkdir _tmp && cd _tmp
          python -m pytest -v --pyargs terminalos