# Full updated workflow
name: Test the built package

on:
  push:
    branches: ["*"]
    tags-ignore: ["v*.*.*"]
  pull_request:

jobs:
  test-built:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Build wheel + sdist
      - name: Build package
        run: |
          python -m pip install build
          python -m build
          ls dist

      # Install in editable mode and test dependencies
      - name: Install package and test dependencies
        run: |
          python -m pip install -e .[test]  # Install with test extras if defined
          # Or if no extras:
          python -m pip install -e .
          python -m pip install pytest

      # Run tests directly (no need for tmp dir)

      - name: Run pytest against installed package
        run: |
          python -m pytest -v --pyargs terminalos
